// GENERATED by scripts/seed.ts — do not edit. `npm run seed` regenerates.
import plates from './plates.json';
import addons from './addons.json';
import copy from './copy.en.json';
import type { Add, Plate } from '../pillars';

export const PLATES = plates as unknown as readonly Plate[];
export const ADDS = addons as unknown as readonly Add[];
export const COPY = copy;
/** sha256 over the canonical JSON bytes of the three files above. */
export const CONTENT_HASH = '6003e27b1e244a2a051fc141a519d3d2344c1079ab88f68c24baa9ccddf0c0d2';
